### ISSUE TITLE
sensor does not show up

### ISSUE THREAD

**Issue by Hypoferalcus** [rootsnet/hass-radon_net#2]
Hi there!

Thanks for the effort of making an integration for radon-net.
Unfortunately I wasn't able to get it working.

As instructed, I just copied the 3 files into the folder /config/custom_components/radon_net/ and added the sample integration  (of course with my login credentials) into the "configuration.yaml" - but unfortunately nothing shows up in the entities - is there any other step to do? Do you have to activate it in the HACS-Section of the UI?

Thanks and kind regards

**Comment by rootsnet** [comment]
Hi,

Please move to Developer Tools -> STATES tab in your browser. 
And then find configured name 'Radon Net Sensor' with Ctrl+F if you configured the name as 'Radon Net Sensor'.

Thanks
