### ISSUE TITLE
Using multiple units in one account

### ISSUE THREAD

**Issue by vobele** [rootsnet/hass-radon_net#4]
I quess this integration only works as long as one unit is registered in the user account on radon-net? (Since the units name in yaml doesn't have to match with the registered unit name on radon-net)

**Comment by rootsnet** [comment]
Yes, that's correct. It was because we didn't have an account with multiple devices to refer to during development.

**Comment by vobele** [comment]
Thank you very much. Not really a problem as the workaround is quite simple (using individual accounts on radon-net for each unit). I hope their cloud service continues for many years to come (and I'm glad to see you're still active). Thumbs up!
